### ISSUE TITLE
Spike: be able to detect the before and after path when using beets.io

### ISSUE THREAD

**Issue by marceljungle** [marceljungle/red-plex#130]
Research of a way to detect the path, before and after the beets transformation:

- Beets has a database in which it saves some information, this should be the first option to check.
- Maybe implementing a beets plugin that will create the relations into the database (https://github.com/marceljungle/red-plex/issues/128).

**Comment by marceljungle** [comment]
There's a way to implement something that may work, and that's using the plugin hook from beets.
After each import, it will execute a command that will make red-plex script create the relation between the source and destination paths for each beets treated album.

```
plugins: hook
hook:
  hooks:
    - event: item_hardlinked
      command: red-plex beets import "{source}" "{destination}"%
```

With that command red-plex will create an entry in the DB for each imported album, specifying the source and destination paths.
